services:
    db:
        image: postgres:17.4-alpine3.20
        container_name: apartments-db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: apartments
        volumes:
            - postgres_data:/var/lib/postgresql/data
    backend:
        build: ./apps/backend
        image: apartments-backend
        container_name: apartments-backend-server
        restart: always
        depends_on:
            - db
        ports:
            - "9090:9090"
            
    frontend:
        build: ./apps/frontend/
        image: apartments-frontend
        container_name: apartments-frontend-server
        restart: always
        environment:
            BACKEND_CONTAINER_URL: http://apartments-backend-server:9090/api/v1/apartment
        depends_on:
            - backend
        ports:
            - "3000:3000"
volumes:
    postgres_data:
